name: Tests

on:
  push:
    branches:
    - felix/compressed-release-artifacts-exp

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/bazel-disk-cache
          key: ${{ runner.os }}-${{ runner.arch }}-bazel-disk-cache
      - name: Setup Linux
        if: runner.os == 'Linux'
        run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get install -y build-essential git clang libc++-dev
      - name: Setup Windows
        if: runner.os == 'Windows'
        run: |
            [System.IO.File]::WriteAllLines((Join-Path -Path $env:USERPROFILE -ChildPath '.bazelrc'), 'startup --output_user_root=C:/tmp')
      - name: Bazel build
        run: |
          bazelisk build --disk_cache=~/bazel-disk-cache  --remote_cache=https://bazel:${{ secrets.BAZEL_CACHE_KEY }}@bazel-remote-cache.devprod.cloudflare.dev --remote_download_toplevel //src/workerd/server:workerd
      - name: Strip debug symbols (Unix)
        if: runner.os != 'Windows'
        run: |
          # bazel makes the output directory read only, make sure we can modify the binary
          chmod +w bazel-bin/src/workerd/server/workerd
          # Strip debug information from the binary, this is acceptable as debug symbols are not
          # generated for the release configuration. Regular symbols are still included.
          ls -l bazel-bin/src/workerd/server/workerd
          strip -S bazel-bin/src/workerd/server/workerd
          ls -l bazel-bin/src/workerd/server/workerd
      - name: Report disk usage
        if: success() || failure()
        shell: bash
        run: |
            BAZEL_OUTPUT_BASE=$(bazel info --ui_event_filters=-WARNING output_base)
            BAZEL_REPOSITORY_CACHE=$(bazel info --ui_event_filters=-WARNING repository_cache)
            echo "Bazel cache usage statistics"
            du -hs -t 1 ~/bazel-disk-cache/* $BAZEL_REPOSITORY_CACHE
            echo "Bazel output usage statistics"
            du -hs -t 1 $BAZEL_OUTPUT_BASE
            echo "Workspace usage statistics"
            du -hs -t 1 $GITHUB_WORKSPACE

